### ISSUE TITLE
Describing Inventarisatie Activiteiten dataset

### ISSUE THREAD

**Issue by kcpveen** [GoldMercy/B.A.U.-Consultants#7]

**Comment by LeCanard272** [comment]
Data exploration is an approach similar to initial data analysis, whereby a data analyst uses visual exploration to understand what is in a dataset and the characteristics of the data, rather than through traditional data management systems.[1] These characteristics can include size or amount of data, completeness of the data, correctness of the data, possible relationships amongst data elements or files/tables in the data.
